"""
Cross-Repository Manager for AutoQA
Handles operations between the action repository and target repository
"""

import os
import subprocess
import json
from pathlib import Path
from typing import List, Dict, Any, Optional
from datetime import datetime


class CrossRepoManager:
    """Manages cross-repository operations for AutoQA action"""
    
    def __init__(self, target_workspace: Path, action_path: Path):
        self.target_workspace = target_workspace
        self.action_path = action_path
        self.github_token = os.getenv('GITHUB_TOKEN')
        self.target_branch = os.getenv('TARGET_BRANCH')
        self.test_directory = os.getenv('TEST_DIRECTORY', 'tests/autoQA')
        
    def commit_test_file(self, code: str, steps: List[str], metadata: Dict[str, Any]) -> Path:
        """Commit generated test file to target repository"""
        
        # Ensure test directory exists in target repo
        test_dir = self.target_workspace / self.test_directory
        test_dir.mkdir(parents=True, exist_ok=True)
        
        # Create __init__.py if it doesn't exist
        init_file = test_dir / "__init__.py"
        if not init_file.exists():
            init_file.write_text("# AutoQA Generated Tests\n")
        
        # Generate test file name
        test_file_path = self._generate_test_file_path(steps, metadata)
        
        # Write test file
        test_content = self._create_test_file_content(code, steps, metadata)
        test_file_path.write_text(test_content)
        
        # Commit to target repository
        self._commit_file_to_repo(test_file_path, steps)
        
        return test_file_path
    
    def _generate_test_file_path(self, steps: List[str], metadata: Dict[str, Any]) -> Path:
        """Generate appropriate file path for the test"""
        test_dir = self.target_workspace / self.test_directory
        
        # Generate descriptive name based on steps
        base_name = self._generate_test_name(steps, metadata)
        
        # Ensure unique filename
        counter = 1
        test_file_path = test_dir / f"test_{base_name}.py"
        
        while test_file_path.exists():
            test_file_path = test_dir / f"test_{base_name}_{counter:03d}.py"
            counter += 1
        
        return test_file_path
    
    def _generate_test_name(self, steps: List[str], metadata: Dict[str, Any]) -> str:
        """Generate a descriptive test name"""
        scenario_type = metadata.get('scenario_type', 'general')
        timestamp = datetime.now().strftime("%Y%m%d_%H%M")
        
        # Create base name from scenario type
        if scenario_type == 'login':
            base_name = f"autoqa_login_{timestamp}"
        elif scenario_type == 'signup':
            base_name = f"autoqa_signup_{timestamp}"
        elif scenario_type == 'dashboard':
            base_name = f"autoqa_dashboard_{timestamp}"
        else:
            base_name = f"autoqa_test_{timestamp}"
        
        return base_name
    
    def _create_test_file_content(self, code: str, steps: List[str], metadata: Dict[str, Any]) -> str:
        """Create complete test file content with metadata"""
        timestamp = datetime.now().isoformat()
        
        header = f'''"""
AutoQA Generated Test
=====================

Generated: {timestamp}
Source: AutoQA PR Description
Steps: {len(steps)}
Scenario Type: {metadata.get('scenario_type', 'general')}

Test Steps:
{chr(10).join(f"{i+1}. {step}" for i, step in enumerate(steps))}

This test was automatically generated by AISquare Studio AutoQA.
Do not modify manually - regenerate through AutoQA if changes are needed.
"""

import pytest
from playwright.sync_api import sync_playwright


class TestAutoQA:
    """AutoQA generated test class"""
    
    @pytest.mark.autoqa
    @pytest.mark.generated
    def test_autoqa_scenario(self):
        """Generated test method"""
        
        # Test configuration (customize as needed)
        config = {{
            'login_url': '{os.getenv("STAGING_LOGIN_URL", "https://staging.example.com/login")}',
            'email': '{os.getenv("STAGING_EMAIL", "test@example.com")}',
            'password': '{os.getenv("STAGING_PASSWORD", "password123")}',
            'headless': True,
            'timeout': 30000
        }}
        
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=config['headless'])
            page = browser.new_page()
            page.set_viewport_size({{"width": 1280, "height": 720}})
            
            try:
                # Execute generated test code
{self._indent_code(code, 16)}
            finally:
                browser.close()


# Standalone execution for testing
if __name__ == "__main__":
    test_instance = TestAutoQA()
    test_instance.test_autoqa_scenario()
    print("✅ AutoQA test completed successfully")
'''
        
        return header
    
    def _indent_code(self, code: str, spaces: int) -> str:
        """Indent code block for proper formatting"""
        indent = ' ' * spaces
        lines = code.split('\n')
        indented_lines = []
        
        for line in lines:
            if line.strip():  # Don't indent empty lines
                indented_lines.append(indent + line)
            else:
                indented_lines.append('')
        
        return '\n'.join(indented_lines)
    
    def _commit_file_to_repo(self, test_file_path: Path, steps: List[str]) -> None:
        """Commit the test file to the target repository"""
        try:
            # Configure git for the action
            subprocess.run(['git', 'config', 'user.name', 'AutoQA Bot'], 
                         cwd=self.target_workspace, check=True)
            subprocess.run(['git', 'config', 'user.email', 'autoqa@aisquare.com'], 
                         cwd=self.target_workspace, check=True)
            
            # Add the test file
            relative_path = test_file_path.relative_to(self.target_workspace)
            subprocess.run(['git', 'add', str(relative_path)], 
                         cwd=self.target_workspace, check=True)
            
            # Create commit message
            commit_message = self._generate_commit_message(steps)
            
            # Commit the file
            subprocess.run(['git', 'commit', '-m', commit_message], 
                         cwd=self.target_workspace, check=True)
            
            print(f"✅ Committed test file: {relative_path}")
            
        except subprocess.CalledProcessError as e:
            print(f"❌ Failed to commit test file: {e}")
            raise
    
    def _generate_commit_message(self, steps: List[str]) -> str:
        """Generate descriptive commit message"""
        step_summary = steps[0] if steps else "AutoQA test"
        return f"AutoQA: Add generated test for '{step_summary}' ({len(steps)} steps)"
    
    def discover_tests(self) -> List[Path]:
        """Discover existing test files in target repository"""
        test_dir = self.target_workspace / self.test_directory
        
        if not test_dir.exists():
            return []
        
        # Find all Python test files
        test_files = []
        for pattern in ['test_*.py', '*_test.py']:
            test_files.extend(test_dir.glob(pattern))
        
        return test_files
    
    def get_test_metadata(self, test_file: Path) -> Optional[Dict[str, Any]]:
        """Extract metadata from test file"""
        try:
            content = test_file.read_text()
            
            # Extract metadata from docstring
            metadata = {}
            
            if 'AutoQA Generated Test' in content:
                metadata['source'] = 'AutoQA'
                metadata['generated'] = True
            
            # Extract other metadata as needed
            
            return metadata
            
        except Exception as e:
            print(f"⚠️ Could not extract metadata from {test_file}: {e}")
            return None
    
    def cleanup_old_tests(self, max_tests: int = 50) -> None:
        """Clean up old AutoQA tests if too many exist"""
        test_files = self.discover_tests()
        autoqa_tests = [f for f in test_files if 'autoqa' in f.name.lower()]
        
        if len(autoqa_tests) > max_tests:
            # Sort by modification time and remove oldest
            autoqa_tests.sort(key=lambda f: f.stat().st_mtime)
            to_remove = autoqa_tests[:len(autoqa_tests) - max_tests]
            
            for test_file in to_remove:
                try:
                    test_file.unlink()
                    print(f"🗑️ Removed old test: {test_file.name}")
                except Exception as e:
                    print(f"⚠️ Could not remove {test_file}: {e}")


# Testing
if __name__ == "__main__":
    # Mock test for development
    import tempfile
    
    with tempfile.TemporaryDirectory() as temp_dir:
        target_workspace = Path(temp_dir)
        action_path = Path('.')
        
        manager = CrossRepoManager(target_workspace, action_path)
        
        test_steps = [
            "Navigate to login page",
            "Enter credentials", 
            "Click login button",
            "Verify success"
        ]
        
        test_code = '''
def run_test(page, config):
    page.goto(config['login_url'])
    page.wait_for_load_state('networkidle')
    assert "login" in page.url.lower()
'''
        
        metadata = {'scenario_type': 'login'}
        
        # This would normally commit to git
        print("Testing CrossRepoManager...")
        print(f"Would commit test with {len(test_steps)} steps")